/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      colors: {
        // Semantic theme tokens — map to CSS vars defined in index.css
        t1:           "var(--text-1)",
        t2:           "var(--text-2)",
        t3:           "var(--text-3)",
        "t-accent":   "var(--text-accent)",
        "theme-bg":   "var(--bg)",
        "theme-surface": "var(--bg-surface)",
        "theme-raised":  "var(--bg-raised)",
        "theme-hover":   "var(--bg-hover)",
        "theme-input":   "var(--bg-input)",
        "theme-muted":   "var(--bg-muted)",
        "theme-border":  "var(--border)",
        "theme-border-md": "var(--border-md)",
        "theme-accent":  "var(--accent)",
        surface: {
          50:  "#f0f1f8",
          100: "#dcdff0",
          200: "#b8bddf",
          300: "#9399cd",
          400: "#6e74bb",
          500: "#4a52a7",
          600: "#363d89",
          700: "#21276a",
          800: "#141850",
          900: "#0c0f38",
          950: "#07071a",
        },
      },
      animation: {
        "fade-in":        "fadeIn 0.35s cubic-bezier(0.16,1,0.3,1) both",
        "slide-up":       "slideUp 0.45s cubic-bezier(0.16,1,0.3,1) both",
        "slide-down":     "slideDown 0.3s cubic-bezier(0.16,1,0.3,1) both",
        "slide-in":       "slideIn 0.3s cubic-bezier(0.16,1,0.3,1) both",
        "slide-in-right": "slideInRight 0.4s cubic-bezier(0.16,1,0.3,1) both",
        "scale-in":       "scaleIn 0.25s cubic-bezier(0.16,1,0.3,1) both",
        "bounce-in":      "bounceIn 0.5s cubic-bezier(0.16,1,0.3,1) both",
        "pulse-slow":     "pulse 3s ease-in-out infinite",
        "float":          "float 6s ease-in-out infinite",
        "ping-slow":      "ping 2s cubic-bezier(0,0,0.2,1) infinite",
        "check-pop":      "checkPop 0.4s cubic-bezier(0.16,1,0.3,1) both",
        "rank-drop":      "rankDrop 0.45s cubic-bezier(0.16,1,0.3,1) both",
        "broadcast-in":   "broadcastIn 0.35s cubic-bezier(0.16,1,0.3,1) both",
        "orbit":          "orbit 12s linear infinite",
      },
      keyframes: {
        fadeIn:       { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        slideUp:      { "0%": { opacity: "0", transform: "translateY(18px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        slideDown:    { "0%": { opacity: "0", transform: "translateY(-10px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        slideIn:      { "0%": { opacity: "0", transform: "translateX(-10px)" }, "100%": { opacity: "1", transform: "translateX(0)" } },
        slideInRight: { "0%": { opacity: "0", transform: "translateX(18px)" }, "100%": { opacity: "1", transform: "translateX(0)" } },
        scaleIn:      { "0%": { opacity: "0", transform: "scale(0.93)" }, "100%": { opacity: "1", transform: "scale(1)" } },
        bounceIn: {
          "0%":   { opacity: "0", transform: "scale(0.5)" },
          "60%":  { opacity: "1", transform: "scale(1.08)" },
          "80%":  { transform: "scale(0.96)" },
          "100%": { transform: "scale(1)" },
        },
        float: { "0%, 100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-8px)" } },
        checkPop: {
          "0%":   { opacity: "0", transform: "scale(0.5) rotate(-10deg)" },
          "100%": { opacity: "1", transform: "scale(1) rotate(0deg)" },
        },
        rankDrop: {
          "0%":   { opacity: "0", transform: "translateY(-12px) scale(0.9)" },
          "100%": { opacity: "1", transform: "translateY(0) scale(1)" },
        },
        broadcastIn: {
          "0%":   { opacity: "0", transform: "translateY(-100%)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        orbit: {
          "0%":   { transform: "rotate(0deg) translateX(110px) rotate(0deg)" },
          "100%": { transform: "rotate(360deg) translateX(110px) rotate(-360deg)" },
        },
      },
    },
  },
  plugins: [],
};
