import type { BlockCategory } from "@scratch/shared";

export type BlockShape = "hat" | "stack" | "c" | "cap" | "reporter" | "boolean";

export interface BlockDef {
  type: string;
  category: BlockCategory;
  label: string;
  color: string;
  shape: BlockShape;
  hint?: string;
  group?: string;
  inputs?: { name: string; type: "number" | "string" | "boolean"; default: any }[];
}

const C: Record<string, string> = {
  game: "#00b894",
  motion: "#4C97FF",
  looks: "#9966FF",
  sound: "#CF63CF",
  events: "#FFBF00",
  control: "#FFAB19",
  operators: "#59C059",
  variables: "#FF8C1A",
  lists: "#FF661A",
  custom: "#FF6680",
  physics: "#5CB1D6",
  sensing: "#5CB1D6",
  pen: "#59A1AA",
  ai: "#FF6B9D",
  environment: "#2ECC71",
  unity: "#22d3ee",
};

export const BLOCK_DEFS: BlockDef[] = [
  /* ═══════════════ Game Systems (33 blocks) ═══════════════ */
  { type: "game_startlevel", category: "game", label: "start level (LEVEL)", color: C.game, shape: "stack", inputs: [{ name: "LEVEL", type: "number", default: 1 }] },
  { type: "game_setstate", category: "game", label: "set game state to (STATE)", color: C.game, shape: "stack", inputs: [{ name: "STATE", type: "string", default: "playing" }] },
  { type: "game_getstate", category: "game", label: "game state", color: C.game, shape: "reporter" },
  { type: "game_setcheckpoint", category: "game", label: "set checkpoint x: (X) y: (Y)", color: C.game, shape: "stack", inputs: [{ name: "X", type: "number", default: 0 }, { name: "Y", type: "number", default: -120 }] },
  { type: "game_respawn", category: "game", label: "respawn at checkpoint", color: C.game, shape: "stack" },
  { type: "game_setplayerstat", category: "game", label: "set player (STAT) to (VALUE)", color: C.game, shape: "stack", inputs: [{ name: "STAT", type: "string", default: "health" }, { name: "VALUE", type: "number", default: 100 }] },
  { type: "game_changeplayerstat", category: "game", label: "change player (STAT) by (VALUE)", color: C.game, shape: "stack", inputs: [{ name: "STAT", type: "string", default: "health" }, { name: "VALUE", type: "number", default: -10 }] },
  { type: "game_playerstat", category: "game", label: "player (STAT)", color: C.game, shape: "reporter", inputs: [{ name: "STAT", type: "string", default: "health" }] },
  { type: "game_spawnenemy", category: "game", label: "spawn enemy (TYPE) at x: (X) y: (Y)", color: C.game, shape: "stack", inputs: [{ name: "TYPE", type: "string", default: "slime" }, { name: "X", type: "number", default: 140 }, { name: "Y", type: "number", default: -100 }] },
  { type: "game_setenemyai", category: "game", label: "set enemy AI to (STYLE)", color: C.game, shape: "stack", inputs: [{ name: "STYLE", type: "string", default: "chase" }] },
  { type: "game_damage", category: "game", label: "damage player by (AMOUNT)", color: C.game, shape: "stack", inputs: [{ name: "AMOUNT", type: "number", default: 10 }] },
  { type: "game_heal", category: "game", label: "heal player by (AMOUNT)", color: C.game, shape: "stack", inputs: [{ name: "AMOUNT", type: "number", default: 10 }] },
  { type: "game_haspowerup", category: "game", label: "has powerup (NAME)?", color: C.game, shape: "boolean", inputs: [{ name: "NAME", type: "string", default: "shield" }] },
  { type: "game_additem", category: "game", label: "add item (ITEM)", color: C.game, shape: "stack", inputs: [{ name: "ITEM", type: "string", default: "coin" }] },
  { type: "game_removeitem", category: "game", label: "remove item (ITEM)", color: C.game, shape: "stack", inputs: [{ name: "ITEM", type: "string", default: "coin" }] },
  { type: "game_hasitem", category: "game", label: "inventory has (ITEM)?", color: C.game, shape: "boolean", inputs: [{ name: "ITEM", type: "string", default: "key" }] },
  { type: "game_setquest", category: "game", label: "set quest (QUEST) to (STATUS)", color: C.game, shape: "stack", inputs: [{ name: "QUEST", type: "string", default: "Find the gem" }, { name: "STATUS", type: "string", default: "active" }] },
  { type: "game_completequest", category: "game", label: "complete quest (QUEST)", color: C.game, shape: "stack", inputs: [{ name: "QUEST", type: "string", default: "Find the gem" }] },
  { type: "game_queststatus", category: "game", label: "quest status (QUEST)", color: C.game, shape: "reporter", inputs: [{ name: "QUEST", type: "string", default: "Find the gem" }] },
  { type: "game_setworldgravity", category: "game", label: "set world gravity (GRAVITY)", color: C.game, shape: "stack", inputs: [{ name: "GRAVITY", type: "number", default: 0.7 }] },
  { type: "game_shakecamera", category: "game", label: "shake camera power (POWER) for (SECS) secs", color: C.game, shape: "stack", inputs: [{ name: "POWER", type: "number", default: 8 }, { name: "SECS", type: "number", default: 0.4 }] },
  { type: "game_showhud", category: "game", label: "show HUD text (TEXT)", color: C.game, shape: "stack", inputs: [{ name: "TEXT", type: "string", default: "Level up!" }] },
  { type: "game_setobjective", category: "game", label: "set objective (TEXT)", color: C.game, shape: "stack", inputs: [{ name: "TEXT", type: "string", default: "Reach the exit" }] },
  { type: "game_save", category: "game", label: "save game to (SLOT)", color: C.game, shape: "stack", inputs: [{ name: "SLOT", type: "string", default: "slot1" }] },
  { type: "game_load", category: "game", label: "load game from (SLOT)", color: C.game, shape: "stack", inputs: [{ name: "SLOT", type: "string", default: "slot1" }] },
  { type: "game_sendnetwork", category: "game", label: "send network event (EVENT)", color: C.game, shape: "stack", inputs: [{ name: "EVENT", type: "string", default: "player_joined" }] },
  { type: "game_networkmessage", category: "game", label: "last network message", color: C.game, shape: "reporter" },
  { type: "game_playanimation", category: "game", label: "play animation (NAME)", color: C.game, shape: "stack", inputs: [{ name: "NAME", type: "string", default: "run" }] },
  { type: "game_setanimspeed", category: "game", label: "set animation speed (SPEED)", color: C.game, shape: "stack", inputs: [{ name: "SPEED", type: "number", default: 1.2 }] },
  { type: "game_musicmode", category: "game", label: "set music mode (MODE)", color: C.game, shape: "stack", inputs: [{ name: "MODE", type: "string", default: "battle" }] },
  { type: "game_playsfx", category: "game", label: "play SFX (NAME)", color: C.game, shape: "stack", inputs: [{ name: "NAME", type: "string", default: "coin" }] },
  { type: "game_comparestat", category: "game", label: "player (STAT) > (VALUE)?", color: C.game, shape: "boolean", inputs: [{ name: "STAT", type: "string", default: "score" }, { name: "VALUE", type: "number", default: 100 }] },
  { type: "game_cooldownready", category: "game", label: "cooldown ready (NAME)?", color: C.game, shape: "boolean", inputs: [{ name: "NAME", type: "string", default: "dash" }] },

  /* ═══════════════ Motion (20 blocks) ═══════════════ */
  { type: "motion_movesteps", category: "motion", label: "move (STEPS) steps", color: C.motion, shape: "stack", hint: "Move forward", inputs: [{ name: "STEPS", type: "number", default: 10 }] },
  { type: "motion_turnright", category: "motion", label: "turn ↻ (DEGREES) degrees", color: C.motion, shape: "stack", inputs: [{ name: "DEGREES", type: "number", default: 15 }] },
  { type: "motion_turnleft", category: "motion", label: "turn ↺ (DEGREES) degrees", color: C.motion, shape: "stack", inputs: [{ name: "DEGREES", type: "number", default: 15 }] },
  { type: "motion_gotoxy", category: "motion", label: "go to x: (X) y: (Y)", color: C.motion, shape: "stack", inputs: [{ name: "X", type: "number", default: 0 }, { name: "Y", type: "number", default: 0 }] },
  { type: "motion_glideto", category: "motion", label: "glide (SECS) secs to x: (X) y: (Y)", color: C.motion, shape: "stack", inputs: [{ name: "SECS", type: "number", default: 1 }, { name: "X", type: "number", default: 0 }, { name: "Y", type: "number", default: 0 }] },
  { type: "motion_changex", category: "motion", label: "change x by (DX)", color: C.motion, shape: "stack", inputs: [{ name: "DX", type: "number", default: 10 }] },
  { type: "motion_changey", category: "motion", label: "change y by (DY)", color: C.motion, shape: "stack", inputs: [{ name: "DY", type: "number", default: 10 }] },
  { type: "motion_setx", category: "motion", label: "set x to (X)", color: C.motion, shape: "stack", inputs: [{ name: "X", type: "number", default: 0 }] },
  { type: "motion_sety", category: "motion", label: "set y to (Y)", color: C.motion, shape: "stack", inputs: [{ name: "Y", type: "number", default: 0 }] },
  { type: "motion_bounceonedge", category: "motion", label: "if on edge, bounce", color: C.motion, shape: "stack" },
  { type: "motion_pointindirection", category: "motion", label: "point in direction (DIR)", color: C.motion, shape: "stack", inputs: [{ name: "DIR", type: "number", default: 90 }] },
  { type: "motion_pointtowards", category: "motion", label: "point towards (TARGET)", color: C.motion, shape: "stack", inputs: [{ name: "TARGET", type: "string", default: "mouse" }] },
  { type: "motion_gotorandom", category: "motion", label: "go to random position", color: C.motion, shape: "stack" },
  { type: "motion_setrotationstyle", category: "motion", label: "set rotation style (STYLE)", color: C.motion, shape: "stack", hint: "left-right, don't rotate, all around", inputs: [{ name: "STYLE", type: "string", default: "all around" }] },
  { type: "motion_glidetosprite", category: "motion", label: "glide (SECS) secs to (TARGET)", color: C.motion, shape: "stack", inputs: [{ name: "SECS", type: "number", default: 1 }, { name: "TARGET", type: "string", default: "mouse" }] },
  { type: "motion_gotosprite", category: "motion", label: "go to (TARGET)", color: C.motion, shape: "stack", inputs: [{ name: "TARGET", type: "string", default: "mouse" }] },
  { type: "motion_xposition", category: "motion", label: "x position", color: C.motion, shape: "reporter" },
  { type: "motion_yposition", category: "motion", label: "y position", color: C.motion, shape: "reporter" },
  { type: "motion_direction", category: "motion", label: "direction", color: C.motion, shape: "reporter" },
  { type: "motion_speed", category: "motion", label: "speed", color: C.motion, shape: "reporter", hint: "How fast the sprite is moving" },
  // — Block / Grid movement —
  { type: "motion_movegrid", category: "motion", label: "move (STEPS) grid steps", color: C.motion, shape: "stack", hint: "Snap-to-grid movement like classic tile games", inputs: [{ name: "STEPS", type: "number", default: 1 }] },
  { type: "motion_setgridsize", category: "motion", label: "set grid size to (SIZE)", color: C.motion, shape: "stack", hint: "Pixels per grid cell (default 40)", inputs: [{ name: "SIZE", type: "number", default: 40 }] },
  { type: "motion_movegridup", category: "motion", label: "move grid up (STEPS) steps", color: C.motion, shape: "stack", inputs: [{ name: "STEPS", type: "number", default: 1 }] },
  { type: "motion_movegriddown", category: "motion", label: "move grid down (STEPS) steps", color: C.motion, shape: "stack", inputs: [{ name: "STEPS", type: "number", default: 1 }] },
  { type: "motion_movegridleft", category: "motion", label: "move grid left (STEPS) steps", color: C.motion, shape: "stack", inputs: [{ name: "STEPS", type: "number", default: 1 }] },
  { type: "motion_movegridright", category: "motion", label: "move grid right (STEPS) steps", color: C.motion, shape: "stack", inputs: [{ name: "STEPS", type: "number", default: 1 }] },
  { type: "motion_snapgrid", category: "motion", label: "snap to grid", color: C.motion, shape: "stack", hint: "Round position to nearest grid cell" },
  // — First-person view —
  { type: "motion_firstperson", category: "motion", label: "set first person view (ON)", color: C.motion, shape: "stack", hint: "Stage follows this sprite's perspective", inputs: [{ name: "ON", type: "boolean", default: true }] },
  { type: "motion_setfov", category: "motion", label: "set field of view to (FOV) degrees", color: C.motion, shape: "stack", inputs: [{ name: "FOV", type: "number", default: 90 }] },

  /* ═══════════════ Looks (22 blocks) ═══════════════ */
  { type: "looks_say", category: "looks", label: "say (MESSAGE)", color: C.looks, shape: "stack", inputs: [{ name: "MESSAGE", type: "string", default: "Hello!" }] },
  { type: "looks_sayforsecs", category: "looks", label: "say (MESSAGE) for (SECS) secs", color: C.looks, shape: "stack", inputs: [{ name: "MESSAGE", type: "string", default: "Hmm..." }, { name: "SECS", type: "number", default: 2 }] },
  { type: "looks_think", category: "looks", label: "think (MESSAGE)", color: C.looks, shape: "stack", inputs: [{ name: "MESSAGE", type: "string", default: "Hmm..." }] },
  { type: "looks_thinkforsecs", category: "looks", label: "think (MESSAGE) for (SECS) secs", color: C.looks, shape: "stack", inputs: [{ name: "MESSAGE", type: "string", default: "Hmm..." }, { name: "SECS", type: "number", default: 2 }] },
  { type: "looks_show", category: "looks", label: "show", color: C.looks, shape: "stack" },
  { type: "looks_hide", category: "looks", label: "hide", color: C.looks, shape: "stack" },
  { type: "looks_setsize", category: "looks", label: "set size to (SIZE) %", color: C.looks, shape: "stack", inputs: [{ name: "SIZE", type: "number", default: 100 }] },
  { type: "looks_changesize", category: "looks", label: "change size by (CHANGE)", color: C.looks, shape: "stack", inputs: [{ name: "CHANGE", type: "number", default: 10 }] },
  { type: "looks_seteffect", category: "looks", label: "set (EFFECT) effect to (VALUE)", color: C.looks, shape: "stack", inputs: [{ name: "EFFECT", type: "string", default: "color" }, { name: "VALUE", type: "number", default: 25 }] },
  { type: "looks_changeeffect", category: "looks", label: "change (EFFECT) effect by (VALUE)", color: C.looks, shape: "stack", inputs: [{ name: "EFFECT", type: "string", default: "color" }, { name: "VALUE", type: "number", default: 25 }] },
  { type: "looks_cleareffects", category: "looks", label: "clear graphic effects", color: C.looks, shape: "stack" },
  // — Named Scratch visual effect shortcuts —
  { type: "effect_setcolor", category: "looks", label: "set color effect to (VALUE)", color: C.looks, shape: "stack", hint: "0-200, shifts hue", inputs: [{ name: "VALUE", type: "number", default: 25 }] },
  { type: "effect_setfisheye", category: "looks", label: "set fisheye effect to (VALUE)", color: C.looks, shape: "stack", hint: "0-100, barrel distortion", inputs: [{ name: "VALUE", type: "number", default: 50 }] },
  { type: "effect_setwhirl", category: "looks", label: "set whirl effect to (VALUE)", color: C.looks, shape: "stack", hint: "-100 to 100, spinning warp", inputs: [{ name: "VALUE", type: "number", default: 60 }] },
  { type: "effect_setmosaic", category: "looks", label: "set mosaic effect to (VALUE)", color: C.looks, shape: "stack", hint: "0-100, tiled copies", inputs: [{ name: "VALUE", type: "number", default: 50 }] },
  { type: "effect_setpixelate", category: "looks", label: "set pixelate effect to (VALUE)", color: C.looks, shape: "stack", hint: "0-100, pixel block size", inputs: [{ name: "VALUE", type: "number", default: 10 }] },
  { type: "effect_setghost", category: "looks", label: "set ghost effect to (VALUE)", color: C.looks, shape: "stack", hint: "0-100, transparency", inputs: [{ name: "VALUE", type: "number", default: 50 }] },
  { type: "effect_setbrightness", category: "looks", label: "set brightness effect to (VALUE)", color: C.looks, shape: "stack", hint: "-100 to 100", inputs: [{ name: "VALUE", type: "number", default: 30 }] },
  { type: "looks_nextcostume", category: "looks", label: "next costume", color: C.looks, shape: "stack" },
  { type: "looks_prevcostume", category: "looks", label: "previous costume", color: C.looks, shape: "stack" },
  { type: "looks_setcostume", category: "looks", label: "switch costume to (NAME)", color: C.looks, shape: "stack", inputs: [{ name: "NAME", type: "string", default: "costume1" }] },
  { type: "looks_goforward", category: "looks", label: "go to front layer", color: C.looks, shape: "stack" },
  { type: "looks_goback", category: "looks", label: "go back (N) layers", color: C.looks, shape: "stack", inputs: [{ name: "N", type: "number", default: 1 }] },
  { type: "looks_setcolor", category: "looks", label: "set color to (COLOR)", color: C.looks, shape: "stack", inputs: [{ name: "COLOR", type: "string", default: "#ff6600" }] },
  { type: "looks_setopacity", category: "looks", label: "set opacity to (PCT) %", color: C.looks, shape: "stack", inputs: [{ name: "PCT", type: "number", default: 100 }] },
  { type: "looks_changeopacity", category: "looks", label: "change opacity by (PCT)", color: C.looks, shape: "stack", inputs: [{ name: "PCT", type: "number", default: -10 }] },
  { type: "looks_setbackdrop", category: "looks", label: "switch backdrop to (BACKDROP)", color: C.looks, shape: "stack", hint: "Use a name, color (#112233), or image URL/data URL", inputs: [{ name: "BACKDROP", type: "string", default: "backdrop1" }] },
  { type: "looks_setbackdropcolor", category: "looks", label: "set backdrop color (COLOR)", color: C.looks, shape: "stack", inputs: [{ name: "COLOR", type: "string", default: "#0a0a1a" }] },
  { type: "looks_setbackdropimage", category: "looks", label: "set backdrop image (URL)", color: C.looks, shape: "stack", hint: "Use image URL or data URL", inputs: [{ name: "URL", type: "string", default: "" }] },
  { type: "looks_clearbackdrop", category: "looks", label: "clear backdrop image", color: C.looks, shape: "stack" },
  { type: "looks_costumename", category: "looks", label: "costume name", color: C.looks, shape: "reporter" },
  { type: "looks_costumenumber", category: "looks", label: "costume number", color: C.looks, shape: "reporter" },
  { type: "looks_size", category: "looks", label: "size", color: C.looks, shape: "reporter" },

  /* ═══════════════ Sound (16 blocks) ═══════════════ */
  { type: "sound_play", category: "sound", label: "play sound (SOUND)", color: C.sound, shape: "stack", inputs: [{ name: "SOUND", type: "string", default: "pop" }] },
  { type: "sound_playuntildone", category: "sound", label: "play sound (SOUND) until done", color: C.sound, shape: "stack", inputs: [{ name: "SOUND", type: "string", default: "pop" }] },
  { type: "sound_stop", category: "sound", label: "stop all sounds", color: C.sound, shape: "stack" },
  { type: "sound_setvolume", category: "sound", label: "set volume to (VOLUME) %", color: C.sound, shape: "stack", inputs: [{ name: "VOLUME", type: "number", default: 100 }] },
  { type: "sound_changevolume", category: "sound", label: "change volume by (VOL)", color: C.sound, shape: "stack", inputs: [{ name: "VOL", type: "number", default: -10 }] },
  { type: "sound_playnote", category: "sound", label: "play note (NOTE) for (BEATS) beats", color: C.sound, shape: "stack", hint: "MIDI note 60 = middle C", inputs: [{ name: "NOTE", type: "number", default: 60 }, { name: "BEATS", type: "number", default: 0.5 }] },
  { type: "sound_playdrum", category: "sound", label: "play drum (DRUM) for (BEATS) beats", color: C.sound, shape: "stack", inputs: [{ name: "DRUM", type: "number", default: 1 }, { name: "BEATS", type: "number", default: 0.25 }] },
  { type: "sound_rest", category: "sound", label: "rest for (BEATS) beats", color: C.sound, shape: "stack", inputs: [{ name: "BEATS", type: "number", default: 0.25 }] },
  { type: "sound_settempo", category: "sound", label: "set tempo to (BPM) bpm", color: C.sound, shape: "stack", inputs: [{ name: "BPM", type: "number", default: 120 }] },
  { type: "sound_changetempo", category: "sound", label: "change tempo by (BPM)", color: C.sound, shape: "stack", inputs: [{ name: "BPM", type: "number", default: 20 }] },
  { type: "sound_setinstrument", category: "sound", label: "set instrument to (INST)", color: C.sound, shape: "stack", hint: "1-21", inputs: [{ name: "INST", type: "number", default: 1 }] },
  { type: "sound_setpitch", category: "sound", label: "set pitch effect to (PITCH)", color: C.sound, shape: "stack", inputs: [{ name: "PITCH", type: "number", default: 0 }] },
  { type: "sound_changepitch", category: "sound", label: "change pitch effect by (PITCH)", color: C.sound, shape: "stack", inputs: [{ name: "PITCH", type: "number", default: 10 }] },
  { type: "sound_setpan", category: "sound", label: "set pan left/right to (PAN)", color: C.sound, shape: "stack", hint: "-100 (left) to 100 (right)", inputs: [{ name: "PAN", type: "number", default: 0 }] },
  { type: "sound_volume", category: "sound", label: "volume", color: C.sound, shape: "reporter" },
  { type: "sound_tempo", category: "sound", label: "tempo", color: C.sound, shape: "reporter" },
  // — Sound choices —
  { type: "sound_playnamed", category: "sound", label: "play (NAME) sound", color: C.sound, shape: "stack", hint: "pop, laser, bell, coin, jump, explosion, click, powerup, hit, whoosh, collect, door, teleport, victory, fail, bounce, error, chime, heartbeat, footstep", inputs: [{ name: "NAME", type: "string", default: "laser" }] },
  { type: "sound_playchord", category: "sound", label: "play chord (NOTES) for (BEATS) beats", color: C.sound, shape: "stack", hint: "Comma-separated MIDI notes e.g. 60,64,67", inputs: [{ name: "NOTES", type: "string", default: "60,64,67" }, { name: "BEATS", type: "number", default: 1 }] },
  { type: "sound_setwaveform", category: "sound", label: "set waveform (WAVE)", color: C.sound, shape: "stack", hint: "sine, square, sawtooth, triangle", inputs: [{ name: "WAVE", type: "string", default: "sine" }] },
  // — Music maker —
  { type: "music_playsequence", category: "sound", label: "play melody (NOTES)", color: C.sound, shape: "stack", hint: "Comma-separated MIDI notes", inputs: [{ name: "NOTES", type: "string", default: "60,62,64,65,67,69,71,72" }] },
  { type: "music_setscale", category: "sound", label: "set scale (SCALE)", color: C.sound, shape: "stack", hint: "major, minor, pentatonic, blues", inputs: [{ name: "SCALE", type: "string", default: "major" }] },
  { type: "music_randommelody", category: "sound", label: "play random melody (LENGTH) notes", color: C.sound, shape: "stack", inputs: [{ name: "LENGTH", type: "number", default: 8 }] },
  { type: "music_setbpm", category: "sound", label: "set BPM to (BPM)", color: C.sound, shape: "stack", inputs: [{ name: "BPM", type: "number", default: 120 }] },

  /* ═══════════════ Events (12 blocks) ═══════════════ */
  { type: "event_whenflagclicked", category: "events", label: "when 🟢 flag clicked", color: C.events, shape: "hat" },
  { type: "event_whenkeypressed", category: "events", label: "when (KEY) key pressed", color: C.events, shape: "hat", inputs: [{ name: "KEY", type: "string", default: "space" }] },
  { type: "event_whenthisspriteclicked", category: "events", label: "when this sprite clicked", color: C.events, shape: "hat" },
  { type: "event_whenbackdropswitches", category: "events", label: "when backdrop switches to (NAME)", color: C.events, shape: "hat", inputs: [{ name: "NAME", type: "string", default: "backdrop1" }] },
  { type: "event_whenbroadcastreceived", category: "events", label: "when I receive (MESSAGE)", color: C.events, shape: "hat", inputs: [{ name: "MESSAGE", type: "string", default: "go" }] },
  { type: "event_broadcast", category: "events", label: "broadcast (MESSAGE)", color: C.events, shape: "stack", inputs: [{ name: "MESSAGE", type: "string", default: "go" }] },
  { type: "event_broadcastandwait", category: "events", label: "broadcast (MESSAGE) and wait", color: C.events, shape: "stack", inputs: [{ name: "MESSAGE", type: "string", default: "go" }] },
  { type: "event_whentimer", category: "events", label: "when timer > (SECS)", color: C.events, shape: "hat", inputs: [{ name: "SECS", type: "number", default: 10 }] },
  { type: "event_whenloudness", category: "events", label: "when loudness > (VOL)", color: C.events, shape: "hat", inputs: [{ name: "VOL", type: "number", default: 50 }] },
  { type: "event_whenstageclick", category: "events", label: "when stage clicked", color: C.events, shape: "hat" },
  { type: "event_whenscenestart", category: "events", label: "when scene starts", color: C.events, shape: "hat" },
  { type: "event_whenvariable", category: "events", label: "when (VAR) > (VAL)", color: C.events, shape: "hat", inputs: [{ name: "VAR", type: "string", default: "score" }, { name: "VAL", type: "number", default: 100 }] },

  /* ═══════════════ Control (18 blocks) ═══════════════ */
  { type: "control_wait", category: "control", label: "wait (DURATION) seconds", color: C.control, shape: "stack", inputs: [{ name: "DURATION", type: "number", default: 1 }] },
  { type: "control_repeat", category: "control", label: "repeat (TIMES)", color: C.control, shape: "c", inputs: [{ name: "TIMES", type: "number", default: 10 }] },
  { type: "control_forever", category: "control", label: "forever", color: C.control, shape: "c" },
  { type: "control_if", category: "control", label: "if ◇ then", color: C.control, shape: "c", inputs: [{ name: "CONDITION", type: "boolean", default: true }] },
  { type: "control_ifelse", category: "control", label: "if ◇ then … else", color: C.control, shape: "c", inputs: [{ name: "CONDITION", type: "boolean", default: true }] },
  { type: "control_ifcompare", category: "control", label: "if (A) (OP) (B) then", color: C.control, shape: "c", hint: "OP: >, <, =, >=, <=, !=", inputs: [{ name: "A", type: "number", default: 0 }, { name: "OP", type: "string", default: ">" }, { name: "B", type: "number", default: 10 }] },
  { type: "control_ifkeypressed", category: "control", label: "if key (KEY) pressed then", color: C.control, shape: "c", inputs: [{ name: "KEY", type: "string", default: "space" }] },
  { type: "control_iftouching", category: "control", label: "if touching (OBJECT) then", color: C.control, shape: "c", inputs: [{ name: "OBJECT", type: "string", default: "edge" }] },
  { type: "control_waituntil", category: "control", label: "wait until ◇", color: C.control, shape: "stack", inputs: [{ name: "CONDITION", type: "boolean", default: true }] },
  { type: "control_repeatuntil", category: "control", label: "repeat until ◇", color: C.control, shape: "c", inputs: [{ name: "CONDITION", type: "boolean", default: false }] },
  { type: "control_stop", category: "control", label: "stop all", color: C.control, shape: "cap" },
  { type: "control_stopthisscript", category: "control", label: "stop this script", color: C.control, shape: "cap" },
  { type: "control_stopothers", category: "control", label: "stop other scripts in sprite", color: C.control, shape: "stack" },
  { type: "control_createclone", category: "control", label: "create clone of (SPRITE)", color: C.control, shape: "stack", inputs: [{ name: "SPRITE", type: "string", default: "myself" }] },
  { type: "control_deleteclone", category: "control", label: "delete this clone", color: C.control, shape: "cap" },
  { type: "control_whencloned", category: "control", label: "when I start as a clone", color: C.control, shape: "hat" },
  { type: "control_foreach", category: "control", label: "for each (VAR) in (LIST)", color: C.control, shape: "c", inputs: [{ name: "VAR", type: "string", default: "item" }, { name: "LIST", type: "string", default: "fruits" }] },
  { type: "control_while", category: "control", label: "while ◇", color: C.control, shape: "c", inputs: [{ name: "CONDITION", type: "boolean", default: true }] },
  { type: "control_trycatch", category: "control", label: "try … catch", color: C.control, shape: "c" },
  { type: "control_waitframes", category: "control", label: "wait (N) frames", color: C.control, shape: "stack", inputs: [{ name: "N", type: "number", default: 1 }] },
  { type: "control_counter", category: "control", label: "counter", color: C.control, shape: "reporter", hint: "Increments each frame in a loop" },

  /* ═══════════════ Operators (24 blocks) ═══════════════ */
  { type: "operator_add", category: "operators", label: "(A) + (B)", color: C.operators, shape: "reporter", inputs: [{ name: "A", type: "number", default: 0 }, { name: "B", type: "number", default: 0 }] },
  { type: "operator_subtract", category: "operators", label: "(A) − (B)", color: C.operators, shape: "reporter", inputs: [{ name: "A", type: "number", default: 0 }, { name: "B", type: "number", default: 0 }] },
  { type: "operator_multiply", category: "operators", label: "(A) × (B)", color: C.operators, shape: "reporter", inputs: [{ name: "A", type: "number", default: 0 }, { name: "B", type: "number", default: 0 }] },
  { type: "operator_divide", category: "operators", label: "(A) ÷ (B)", color: C.operators, shape: "reporter", inputs: [{ name: "A", type: "number", default: 0 }, { name: "B", type: "number", default: 0 }] },
  { type: "operator_mod", category: "operators", label: "(A) mod (B)", color: C.operators, shape: "reporter", inputs: [{ name: "A", type: "number", default: 10 }, { name: "B", type: "number", default: 3 }] },
  { type: "operator_round", category: "operators", label: "round (A)", color: C.operators, shape: "reporter", inputs: [{ name: "A", type: "number", default: 3.7 }] },
  { type: "operator_random", category: "operators", label: "pick random (FROM) to (TO)", color: C.operators, shape: "reporter", inputs: [{ name: "FROM", type: "number", default: 1 }, { name: "TO", type: "number", default: 10 }] },
  { type: "operator_gt", category: "operators", label: "(A) > (B)", color: C.operators, shape: "boolean", inputs: [{ name: "A", type: "number", default: 0 }, { name: "B", type: "number", default: 50 }] },
  { type: "operator_lt", category: "operators", label: "(A) < (B)", color: C.operators, shape: "boolean", inputs: [{ name: "A", type: "number", default: 0 }, { name: "B", type: "number", default: 50 }] },
  { type: "operator_equals", category: "operators", label: "(A) = (B)", color: C.operators, shape: "boolean", inputs: [{ name: "A", type: "number", default: 0 }, { name: "B", type: "number", default: 50 }] },
  { type: "operator_and", category: "operators", label: "◇ and ◇", color: C.operators, shape: "boolean", inputs: [{ name: "A", type: "boolean", default: true }, { name: "B", type: "boolean", default: true }] },
  { type: "operator_or", category: "operators", label: "◇ or ◇", color: C.operators, shape: "boolean", inputs: [{ name: "A", type: "boolean", default: false }, { name: "B", type: "boolean", default: false }] },
  { type: "operator_not", category: "operators", label: "not ◇", color: C.operators, shape: "boolean", inputs: [{ name: "A", type: "boolean", default: false }] },
  { type: "operator_join", category: "operators", label: "join (A) (B)", color: C.operators, shape: "reporter", inputs: [{ name: "A", type: "string", default: "hello " }, { name: "B", type: "string", default: "world" }] },
  { type: "operator_length", category: "operators", label: "length of (TEXT)", color: C.operators, shape: "reporter", inputs: [{ name: "TEXT", type: "string", default: "hello" }] },
  { type: "operator_letterof", category: "operators", label: "letter (N) of (TEXT)", color: C.operators, shape: "reporter", inputs: [{ name: "N", type: "number", default: 1 }, { name: "TEXT", type: "string", default: "hello" }] },
  { type: "operator_contains", category: "operators", label: "(TEXT) contains (SEARCH)?", color: C.operators, shape: "boolean", inputs: [{ name: "TEXT", type: "string", default: "hello world" }, { name: "SEARCH", type: "string", default: "world" }] },
  { type: "operator_mathop", category: "operators", label: "(OP) of (A)", color: C.operators, shape: "reporter", inputs: [{ name: "OP", type: "string", default: "abs" }, { name: "A", type: "number", default: -5 }] },
  { type: "operator_power", category: "operators", label: "(A) ^ (B)", color: C.operators, shape: "reporter", hint: "Exponent / power", inputs: [{ name: "A", type: "number", default: 2 }, { name: "B", type: "number", default: 3 }] },
  { type: "operator_floor", category: "operators", label: "floor (A)", color: C.operators, shape: "reporter", inputs: [{ name: "A", type: "number", default: 3.7 }] },
  { type: "operator_ceil", category: "operators", label: "ceiling (A)", color: C.operators, shape: "reporter", inputs: [{ name: "A", type: "number", default: 3.2 }] },
  { type: "operator_min", category: "operators", label: "min of (A) and (B)", color: C.operators, shape: "reporter", inputs: [{ name: "A", type: "number", default: 5 }, { name: "B", type: "number", default: 10 }] },
  { type: "operator_max", category: "operators", label: "max of (A) and (B)", color: C.operators, shape: "reporter", inputs: [{ name: "A", type: "number", default: 5 }, { name: "B", type: "number", default: 10 }] },
  { type: "operator_clamp", category: "operators", label: "clamp (A) between (LO) and (HI)", color: C.operators, shape: "reporter", inputs: [{ name: "A", type: "number", default: 50 }, { name: "LO", type: "number", default: 0 }, { name: "HI", type: "number", default: 100 }] },

  /* ═══════════════ Variables (8 blocks) ═══════════════ */
  { type: "variable_set", category: "variables", label: "set (VAR) to (VALUE)", color: C.variables, shape: "stack", inputs: [{ name: "VAR", type: "string", default: "score" }, { name: "VALUE", type: "number", default: 0 }] },
  { type: "variable_change", category: "variables", label: "change (VAR) by (VALUE)", color: C.variables, shape: "stack", inputs: [{ name: "VAR", type: "string", default: "score" }, { name: "VALUE", type: "number", default: 1 }] },
  { type: "variable_show", category: "variables", label: "show variable (VAR)", color: C.variables, shape: "stack", inputs: [{ name: "VAR", type: "string", default: "score" }] },
  { type: "variable_hide", category: "variables", label: "hide variable (VAR)", color: C.variables, shape: "stack", inputs: [{ name: "VAR", type: "string", default: "score" }] },
  { type: "variable_get", category: "variables", label: "value of (VAR)", color: C.variables, shape: "reporter", inputs: [{ name: "VAR", type: "string", default: "score" }] },
  { type: "variable_setglobal", category: "variables", label: "set global (VAR) to (VALUE)", color: C.variables, shape: "stack", inputs: [{ name: "VAR", type: "string", default: "highScore" }, { name: "VALUE", type: "number", default: 0 }] },
  { type: "variable_changeglobal", category: "variables", label: "change global (VAR) by (VALUE)", color: C.variables, shape: "stack", inputs: [{ name: "VAR", type: "string", default: "highScore" }, { name: "VALUE", type: "number", default: 1 }] },
  { type: "variable_getglobal", category: "variables", label: "global (VAR)", color: C.variables, shape: "reporter", inputs: [{ name: "VAR", type: "string", default: "highScore" }] },
  { type: "variable_countersetup", category: "variables", label: "set counter (VAR) start (START) step (STEP)", color: C.variables, shape: "stack", hint: "Custom counter config", inputs: [{ name: "VAR", type: "string", default: "score" }, { name: "START", type: "number", default: 0 }, { name: "STEP", type: "number", default: 1 }] },
  { type: "variable_countertick", category: "variables", label: "count (VAR)", color: C.variables, shape: "stack", hint: "Increments by configured step", inputs: [{ name: "VAR", type: "string", default: "score" }] },
  { type: "variable_counterinc", category: "variables", label: "increase counter (VAR)", color: C.variables, shape: "stack", inputs: [{ name: "VAR", type: "string", default: "score" }] },
  { type: "variable_counterdec", category: "variables", label: "decrease counter (VAR)", color: C.variables, shape: "stack", inputs: [{ name: "VAR", type: "string", default: "score" }] },
  { type: "variable_counterreset", category: "variables", label: "reset counter (VAR)", color: C.variables, shape: "stack", inputs: [{ name: "VAR", type: "string", default: "score" }] },
  { type: "variable_countershow", category: "variables", label: "show counter (VAR)", color: C.variables, shape: "stack", inputs: [{ name: "VAR", type: "string", default: "score" }] },
  { type: "variable_counterhide", category: "variables", label: "hide counter (VAR)", color: C.variables, shape: "stack", inputs: [{ name: "VAR", type: "string", default: "score" }] },
  { type: "variable_countervalue", category: "variables", label: "counter value (VAR)", color: C.variables, shape: "reporter", inputs: [{ name: "VAR", type: "string", default: "score" }] },

  /* ═══════════════ Lists (14 blocks) ═══════════════ */
  { type: "list_add", category: "lists", label: "add (ITEM) to (LIST)", color: C.lists, shape: "stack", inputs: [{ name: "ITEM", type: "string", default: "apple" }, { name: "LIST", type: "string", default: "fruits" }] },
  { type: "list_delete", category: "lists", label: "delete item (INDEX) of (LIST)", color: C.lists, shape: "stack", inputs: [{ name: "INDEX", type: "number", default: 1 }, { name: "LIST", type: "string", default: "fruits" }] },
  { type: "list_deleteall", category: "lists", label: "delete all of (LIST)", color: C.lists, shape: "stack", inputs: [{ name: "LIST", type: "string", default: "fruits" }] },
  { type: "list_insert", category: "lists", label: "insert (ITEM) at (INDEX) of (LIST)", color: C.lists, shape: "stack", inputs: [{ name: "ITEM", type: "string", default: "banana" }, { name: "INDEX", type: "number", default: 1 }, { name: "LIST", type: "string", default: "fruits" }] },
  { type: "list_replace", category: "lists", label: "replace item (INDEX) of (LIST) with (ITEM)", color: C.lists, shape: "stack", inputs: [{ name: "INDEX", type: "number", default: 1 }, { name: "LIST", type: "string", default: "fruits" }, { name: "ITEM", type: "string", default: "grape" }] },
  { type: "list_item", category: "lists", label: "item (INDEX) of (LIST)", color: C.lists, shape: "reporter", inputs: [{ name: "INDEX", type: "number", default: 1 }, { name: "LIST", type: "string", default: "fruits" }] },
  { type: "list_length", category: "lists", label: "length of (LIST)", color: C.lists, shape: "reporter", inputs: [{ name: "LIST", type: "string", default: "fruits" }] },
  { type: "list_contains", category: "lists", label: "(LIST) contains (ITEM)?", color: C.lists, shape: "boolean", inputs: [{ name: "LIST", type: "string", default: "fruits" }, { name: "ITEM", type: "string", default: "apple" }] },
  { type: "list_indexof", category: "lists", label: "index of (ITEM) in (LIST)", color: C.lists, shape: "reporter", inputs: [{ name: "ITEM", type: "string", default: "apple" }, { name: "LIST", type: "string", default: "fruits" }] },
  { type: "list_show", category: "lists", label: "show list (LIST)", color: C.lists, shape: "stack", inputs: [{ name: "LIST", type: "string", default: "fruits" }] },
  { type: "list_hide", category: "lists", label: "hide list (LIST)", color: C.lists, shape: "stack", inputs: [{ name: "LIST", type: "string", default: "fruits" }] },
  { type: "list_randomitem", category: "lists", label: "random item of (LIST)", color: C.lists, shape: "reporter", inputs: [{ name: "LIST", type: "string", default: "fruits" }] },
  { type: "list_lastitem", category: "lists", label: "last item of (LIST)", color: C.lists, shape: "reporter", inputs: [{ name: "LIST", type: "string", default: "fruits" }] },
  { type: "list_reverse", category: "lists", label: "reverse (LIST)", color: C.lists, shape: "stack", inputs: [{ name: "LIST", type: "string", default: "fruits" }] },

  /* ═══════════════ Physics (14 blocks) ═══════════════ */
  { type: "physics_setgravity", category: "physics", label: "set gravity to (G)", color: C.physics, shape: "stack", inputs: [{ name: "G", type: "number", default: 10 }] },
  { type: "physics_setvelocity", category: "physics", label: "set speed x: (VX) y: (VY)", color: C.physics, shape: "stack", inputs: [{ name: "VX", type: "number", default: 0 }, { name: "VY", type: "number", default: 5 }] },
  { type: "physics_applyforce", category: "physics", label: "push with x: (FX) y: (FY)", color: C.physics, shape: "stack", inputs: [{ name: "FX", type: "number", default: 0 }, { name: "FY", type: "number", default: -10 }] },
  { type: "physics_bounce", category: "physics", label: "bounce off edges", color: C.physics, shape: "stack" },
  { type: "physics_setfriction", category: "physics", label: "set friction to (F)", color: C.physics, shape: "stack", inputs: [{ name: "F", type: "number", default: 0.1 }] },
  { type: "physics_collision", category: "physics", label: "when bumping into (SPRITE)", color: C.physics, shape: "hat", inputs: [{ name: "SPRITE", type: "string", default: "any" }] },
  { type: "physics_setmass", category: "physics", label: "set weight to (M)", color: C.physics, shape: "stack", inputs: [{ name: "M", type: "number", default: 1 }] },
  { type: "physics_setbouncy", category: "physics", label: "set bounciness to (B)", color: C.physics, shape: "stack", inputs: [{ name: "B", type: "number", default: 0.5 }] },
  { type: "physics_spin", category: "physics", label: "spin at (SPEED) deg/sec", color: C.physics, shape: "stack", inputs: [{ name: "SPEED", type: "number", default: 90 }] },
  { type: "physics_attract", category: "physics", label: "attract towards x: (X) y: (Y) force (F)", color: C.physics, shape: "stack", inputs: [{ name: "X", type: "number", default: 0 }, { name: "Y", type: "number", default: 0 }, { name: "F", type: "number", default: 5 }] },
  { type: "physics_setdrag", category: "physics", label: "set air resistance to (D)", color: C.physics, shape: "stack", inputs: [{ name: "D", type: "number", default: 0.05 }] },
  { type: "physics_isonground", category: "physics", label: "on ground?", color: C.physics, shape: "boolean" },
  { type: "physics_velocity_x", category: "physics", label: "x speed", color: C.physics, shape: "reporter" },
  { type: "physics_velocity_y", category: "physics", label: "y speed", color: C.physics, shape: "reporter" },
  { type: "physics_jump", category: "physics", label: "jump with power (POWER)", color: C.physics, shape: "stack", hint: "Jump upward (only when on ground)", inputs: [{ name: "POWER", type: "number", default: 12 }] },
  { type: "physics_walljump", category: "physics", label: "wall jump power (POWER)", color: C.physics, shape: "stack", inputs: [{ name: "POWER", type: "number", default: 10 }] },

  /* ═══════════════ Sensing (22 blocks) ═══════════════ */
  { type: "sensing_touching", category: "sensing", label: "touching (OBJECT)?", color: C.sensing, shape: "boolean", inputs: [{ name: "OBJECT", type: "string", default: "edge" }] },
  { type: "sensing_touchingcolor", category: "sensing", label: "touching color (COLOR)?", color: C.sensing, shape: "boolean", inputs: [{ name: "COLOR", type: "string", default: "#ff0000" }] },
  { type: "sensing_distanceto", category: "sensing", label: "distance to (OBJECT)", color: C.sensing, shape: "reporter", inputs: [{ name: "OBJECT", type: "string", default: "mouse" }] },
  { type: "sensing_keypressed", category: "sensing", label: "key (KEY) pressed?", color: C.sensing, shape: "boolean", inputs: [{ name: "KEY", type: "string", default: "space" }] },
  { type: "sensing_mousedown", category: "sensing", label: "mouse down?", color: C.sensing, shape: "boolean" },
  { type: "sensing_mousex", category: "sensing", label: "mouse x", color: C.sensing, shape: "reporter" },
  { type: "sensing_mousey", category: "sensing", label: "mouse y", color: C.sensing, shape: "reporter" },
  { type: "sensing_ask", category: "sensing", label: "ask (QUESTION) and wait", color: C.sensing, shape: "stack", inputs: [{ name: "QUESTION", type: "string", default: "What's your name?" }] },
  { type: "sensing_answer", category: "sensing", label: "answer", color: C.sensing, shape: "reporter" },
  { type: "sensing_timer", category: "sensing", label: "timer", color: C.sensing, shape: "reporter" },
  { type: "sensing_resettimer", category: "sensing", label: "reset timer", color: C.sensing, shape: "stack" },
  { type: "sensing_loudness", category: "sensing", label: "loudness", color: C.sensing, shape: "reporter" },
  { type: "sensing_dayssince2000", category: "sensing", label: "days since 2000", color: C.sensing, shape: "reporter" },
  { type: "sensing_username", category: "sensing", label: "username", color: C.sensing, shape: "reporter" },
  { type: "sensing_year", category: "sensing", label: "current year", color: C.sensing, shape: "reporter" },
  { type: "sensing_month", category: "sensing", label: "current month", color: C.sensing, shape: "reporter" },
  { type: "sensing_day", category: "sensing", label: "current day", color: C.sensing, shape: "reporter" },
  { type: "sensing_hour", category: "sensing", label: "current hour", color: C.sensing, shape: "reporter" },
  { type: "sensing_minute", category: "sensing", label: "current minute", color: C.sensing, shape: "reporter" },
  { type: "sensing_second", category: "sensing", label: "current second", color: C.sensing, shape: "reporter" },
  { type: "sensing_colorat", category: "sensing", label: "color at x: (X) y: (Y)", color: C.sensing, shape: "reporter", inputs: [{ name: "X", type: "number", default: 0 }, { name: "Y", type: "number", default: 0 }] },
  { type: "sensing_draggable", category: "sensing", label: "set drag mode (MODE)", color: C.sensing, shape: "stack", inputs: [{ name: "MODE", type: "string", default: "draggable" }] },

  /* ═══════════════ My Blocks (6 blocks) ═══════════════ */
  { type: "custom_define", category: "custom", label: "define (NAME)", color: C.custom, shape: "hat", inputs: [{ name: "NAME", type: "string", default: "myBlock" }] },
  { type: "custom_call", category: "custom", label: "run (NAME)", color: C.custom, shape: "stack", inputs: [{ name: "NAME", type: "string", default: "myBlock" }] },
  { type: "custom_definewithparam", category: "custom", label: "define (NAME) with (PARAM)", color: C.custom, shape: "hat", inputs: [{ name: "NAME", type: "string", default: "myFunc" }, { name: "PARAM", type: "string", default: "n" }] },
  { type: "custom_callwitharg", category: "custom", label: "run (NAME) with (ARG)", color: C.custom, shape: "stack", inputs: [{ name: "NAME", type: "string", default: "myFunc" }, { name: "ARG", type: "number", default: 10 }] },
  { type: "custom_return", category: "custom", label: "return (VALUE)", color: C.custom, shape: "cap", inputs: [{ name: "VALUE", type: "number", default: 0 }] },
  { type: "custom_param", category: "custom", label: "parameter (NAME)", color: C.custom, shape: "reporter", inputs: [{ name: "NAME", type: "string", default: "n" }] },

  /* ═══════════════ AI (28 blocks) ═══════════════ */
  // — Chat & text —
  { type: "ai_whenresponse", category: "ai", label: "when AI responds", color: C.ai, shape: "hat" },
  { type: "ai_ask", category: "ai", label: "ask AI (PROMPT)", color: C.ai, shape: "stack", inputs: [{ name: "PROMPT", type: "string", default: "Tell me a joke" }] },
  { type: "ai_response", category: "ai", label: "AI response", color: C.ai, shape: "reporter" },
  { type: "ai_complete", category: "ai", label: "AI complete (TEXT)", color: C.ai, shape: "stack", inputs: [{ name: "TEXT", type: "string", default: "Once upon a time" }] },
  { type: "ai_say_smart", category: "ai", label: "AI say something about (TOPIC)", color: C.ai, shape: "stack", inputs: [{ name: "TOPIC", type: "string", default: "space" }] },
  { type: "ai_code_explain", category: "ai", label: "explain my code", color: C.ai, shape: "stack" },
  { type: "ai_suggest_next", category: "ai", label: "AI suggest next block", color: C.ai, shape: "stack" },
  // — Classification & analysis —
  { type: "ai_classify", category: "ai", label: "classify (TEXT) as (CATEGORIES)", color: C.ai, shape: "stack", inputs: [{ name: "TEXT", type: "string", default: "I love cats" }, { name: "CATEGORIES", type: "string", default: "happy,sad,neutral" }] },
  { type: "ai_sentiment", category: "ai", label: "sentiment of (TEXT)", color: C.ai, shape: "stack", inputs: [{ name: "TEXT", type: "string", default: "This is amazing!" }] },
  { type: "ai_emotion", category: "ai", label: "AI emotion of (TEXT)", color: C.ai, shape: "stack", inputs: [{ name: "TEXT", type: "string", default: "I'm so excited!" }] },
  { type: "ai_decide", category: "ai", label: "AI should I (QUESTION)?", color: C.ai, shape: "stack", inputs: [{ name: "QUESTION", type: "string", default: "jump now" }] },
  // — Language —
  { type: "ai_translate", category: "ai", label: "translate (TEXT) to (LANG)", color: C.ai, shape: "stack", inputs: [{ name: "TEXT", type: "string", default: "Hello" }, { name: "LANG", type: "string", default: "Spanish" }] },
  { type: "ai_rhyme", category: "ai", label: "AI rhyme with (WORD)", color: C.ai, shape: "stack", inputs: [{ name: "WORD", type: "string", default: "cat" }] },
  { type: "ai_generate_story", category: "ai", label: "AI story about (TOPIC)", color: C.ai, shape: "stack", inputs: [{ name: "TOPIC", type: "string", default: "a brave cat" }] },
  { type: "ai_poem", category: "ai", label: "AI write poem about (TOPIC)", color: C.ai, shape: "stack", inputs: [{ name: "TOPIC", type: "string", default: "the ocean" }] },
  { type: "ai_summarize", category: "ai", label: "AI summarize (TEXT)", color: C.ai, shape: "stack", inputs: [{ name: "TEXT", type: "string", default: "A long story..." }] },
  // — Creative / generative —
  { type: "ai_image_describe", category: "ai", label: "describe image (DESCRIPTION)", color: C.ai, shape: "stack", inputs: [{ name: "DESCRIPTION", type: "string", default: "a red spaceship" }] },
  { type: "ai_generate_image", category: "ai", label: "🖼️ AI generate image (PROMPT)", color: C.ai, shape: "stack", hint: "Creates a picture from a text prompt", inputs: [{ name: "PROMPT", type: "string", default: "a cute robot waving" }] },
  { type: "ai_generate_3dmodel", category: "ai", label: "🧊 AI make 3D model (PROMPT)", color: C.ai, shape: "stack", hint: "Generates a 3D shape from a description", inputs: [{ name: "PROMPT", type: "string", default: "a small house" }] },
  { type: "ai_set_photo", category: "ai", label: "📷 AI set costume from photo (PROMPT)", color: C.ai, shape: "stack", hint: "Sets the sprite costume to an AI-generated image", inputs: [{ name: "PROMPT", type: "string", default: "a cartoon cat" }] },
  { type: "ai_drawing", category: "ai", label: "🎨 AI draw on stage (PROMPT)", color: C.ai, shape: "stack", hint: "Draws an AI-generated image directly on the stage", inputs: [{ name: "PROMPT", type: "string", default: "a sunset landscape" }] },
  { type: "ai_generate_sound", category: "ai", label: "🔊 AI make sound (PROMPT)", color: C.ai, shape: "stack", hint: "Generates a sound effect description", inputs: [{ name: "PROMPT", type: "string", default: "laser zap" }] },
  { type: "ai_name_generator", category: "ai", label: "AI random name for (TYPE)", color: C.ai, shape: "stack", inputs: [{ name: "TYPE", type: "string", default: "character" }] },
  { type: "ai_color_palette", category: "ai", label: "AI color palette for (MOOD)", color: C.ai, shape: "stack", hint: "Generates colors matching a mood", inputs: [{ name: "MOOD", type: "string", default: "happy" }] },
  // — Game AI —
  { type: "ai_npc_dialog", category: "ai", label: "🗣️ AI NPC says about (TOPIC)", color: C.ai, shape: "stack", hint: "NPC character dialog", inputs: [{ name: "TOPIC", type: "string", default: "the quest" }] },
  { type: "ai_hint", category: "ai", label: "💡 AI give hint for (TASK)", color: C.ai, shape: "stack", inputs: [{ name: "TASK", type: "string", default: "solving the puzzle" }] },
  { type: "ai_quiz_question", category: "ai", label: "❓ AI quiz about (TOPIC)", color: C.ai, shape: "stack", inputs: [{ name: "TOPIC", type: "string", default: "science" }] },
  { type: "ai_trivia", category: "ai", label: "🧠 AI trivia about (TOPIC)", color: C.ai, shape: "stack", inputs: [{ name: "TOPIC", type: "string", default: "animals" }] },

  /* ═══════════════ Pen (12 blocks) ═══════════════ */
  { type: "pen_pendown", category: "pen", label: "pen down", color: C.pen, shape: "stack", hint: "Start drawing" },
  { type: "pen_penup", category: "pen", label: "pen up", color: C.pen, shape: "stack", hint: "Stop drawing" },
  { type: "pen_clear", category: "pen", label: "erase all", color: C.pen, shape: "stack", hint: "Clear all pen marks" },
  { type: "pen_stamp", category: "pen", label: "stamp", color: C.pen, shape: "stack", hint: "Stamp a copy of the sprite" },
  { type: "pen_setpencolor", category: "pen", label: "set pen color to (COLOR)", color: C.pen, shape: "stack", inputs: [{ name: "COLOR", type: "string", default: "#4C97FF" }] },
  { type: "pen_changepencolor", category: "pen", label: "change pen color by (CHANGE)", color: C.pen, shape: "stack", inputs: [{ name: "CHANGE", type: "number", default: 10 }] },
  { type: "pen_setpensize", category: "pen", label: "set pen size to (SIZE)", color: C.pen, shape: "stack", inputs: [{ name: "SIZE", type: "number", default: 2 }] },
  { type: "pen_changepensize", category: "pen", label: "change pen size by (CHANGE)", color: C.pen, shape: "stack", inputs: [{ name: "CHANGE", type: "number", default: 1 }] },
  { type: "pen_setpenshade", category: "pen", label: "set pen shade to (SHADE)", color: C.pen, shape: "stack", inputs: [{ name: "SHADE", type: "number", default: 50 }] },
  { type: "pen_setpentransparency", category: "pen", label: "set pen transparency to (PCT) %", color: C.pen, shape: "stack", inputs: [{ name: "PCT", type: "number", default: 0 }] },
  { type: "pen_drawdot", category: "pen", label: "draw dot at x: (X) y: (Y)", color: C.pen, shape: "stack", inputs: [{ name: "X", type: "number", default: 0 }, { name: "Y", type: "number", default: 0 }] },
  { type: "pen_drawline", category: "pen", label: "draw line to x: (X) y: (Y)", color: C.pen, shape: "stack", inputs: [{ name: "X", type: "number", default: 100 }, { name: "Y", type: "number", default: 0 }] },
  // — Pen+ enhanced blocks —
  { type: "pen_drawcircle", category: "pen", label: "draw circle radius (R)", color: C.pen, shape: "stack", inputs: [{ name: "R", type: "number", default: 40 }] },
  { type: "pen_drawrect", category: "pen", label: "draw rectangle (W) x (H)", color: C.pen, shape: "stack", inputs: [{ name: "W", type: "number", default: 80 }, { name: "H", type: "number", default: 50 }] },
  { type: "pen_fill", category: "pen", label: "fill circle radius (R)", color: C.pen, shape: "stack", hint: "Draw a filled circle", inputs: [{ name: "R", type: "number", default: 30 }] },
  { type: "pen_writetext", category: "pen", label: "write (TEXT) size (SIZE)", color: C.pen, shape: "stack", inputs: [{ name: "TEXT", type: "string", default: "Hello" }, { name: "SIZE", type: "number", default: 20 }] },
  { type: "pen_rainbow", category: "pen", label: "set pen to rainbow speed (SPEED)", color: C.pen, shape: "stack", hint: "Cycles pen color through rainbow", inputs: [{ name: "SPEED", type: "number", default: 5 }] },
  { type: "pen_setstyle", category: "pen", label: "set pen style (STYLE)", color: C.pen, shape: "stack", hint: "solid, dashed, dotted, glow", inputs: [{ name: "STYLE", type: "string", default: "solid" }] },

  /* ═══════════════ 3D Environments (22 blocks) ═══════════════ */
  // — Scene & Backdrop —
  { type: "env_setscene", category: "environment", label: "set 3D scene to (SCENE)", color: C.environment, shape: "stack", hint: "dojo, forest, desert, snow, city, space, ocean, volcano, cave, neon", inputs: [{ name: "SCENE", type: "string", default: "forest" }] },
  { type: "env_setsky", category: "environment", label: "set sky color (COLOR)", color: C.environment, shape: "stack", inputs: [{ name: "COLOR", type: "string", default: "#87CEEB" }] },
  { type: "env_setground", category: "environment", label: "set ground color (COLOR)", color: C.environment, shape: "stack", inputs: [{ name: "COLOR", type: "string", default: "#2d5a3a" }] },
  { type: "env_setfog", category: "environment", label: "set fog density (DENSITY)", color: C.environment, shape: "stack", hint: "0 = none, 100 = thick", inputs: [{ name: "DENSITY", type: "number", default: 30 }] },
  { type: "env_settime", category: "environment", label: "set time of day (TIME)", color: C.environment, shape: "stack", hint: "sunrise, day, sunset, night", inputs: [{ name: "TIME", type: "string", default: "day" }] },
  // — Camera —
  { type: "env_movecamera", category: "environment", label: "move camera to x: (X) y: (Y) z: (Z)", color: C.environment, shape: "stack", inputs: [{ name: "X", type: "number", default: 0 }, { name: "Y", type: "number", default: 5 }, { name: "Z", type: "number", default: 10 }] },
  { type: "env_rotatecamera", category: "environment", label: "rotate camera (DEGREES) degrees", color: C.environment, shape: "stack", inputs: [{ name: "DEGREES", type: "number", default: 15 }] },
  { type: "env_zoomcamera", category: "environment", label: "set camera zoom (ZOOM)", color: C.environment, shape: "stack", hint: "30 = zoomed in, 90 = wide", inputs: [{ name: "ZOOM", type: "number", default: 60 }] },
  { type: "env_followsprite", category: "environment", label: "camera follow (SPRITE)", color: C.environment, shape: "stack", inputs: [{ name: "SPRITE", type: "string", default: "myself" }] },
  { type: "env_shakecamera3d", category: "environment", label: "shake 3D camera (POWER)", color: C.environment, shape: "stack", inputs: [{ name: "POWER", type: "number", default: 5 }] },
  // — Lighting —
  { type: "env_setambient", category: "environment", label: "set ambient light (BRIGHTNESS) %", color: C.environment, shape: "stack", inputs: [{ name: "BRIGHTNESS", type: "number", default: 50 }] },
  { type: "env_setlightcolor", category: "environment", label: "set light color (COLOR)", color: C.environment, shape: "stack", inputs: [{ name: "COLOR", type: "string", default: "#ffffff" }] },
  { type: "env_addsunlight", category: "environment", label: "add sunlight from angle (ANGLE)", color: C.environment, shape: "stack", inputs: [{ name: "ANGLE", type: "number", default: 45 }] },
  { type: "env_addspotlight", category: "environment", label: "add spotlight at x: (X) y: (Y) z: (Z)", color: C.environment, shape: "stack", inputs: [{ name: "X", type: "number", default: 0 }, { name: "Y", type: "number", default: 10 }, { name: "Z", type: "number", default: 0 }] },
  // — 3D Objects —
  { type: "env_spawn3d", category: "environment", label: "spawn (SHAPE) at x: (X) y: (Y) z: (Z)", color: C.environment, shape: "stack", hint: "box, sphere, cylinder, cone, torus", inputs: [{ name: "SHAPE", type: "string", default: "box" }, { name: "X", type: "number", default: 0 }, { name: "Y", type: "number", default: 0 }, { name: "Z", type: "number", default: 0 }] },
  { type: "env_set3dcolor", category: "environment", label: "set 3D color (COLOR)", color: C.environment, shape: "stack", inputs: [{ name: "COLOR", type: "string", default: "#4C97FF" }] },
  { type: "env_set3dscale", category: "environment", label: "set 3D scale (SCALE)", color: C.environment, shape: "stack", inputs: [{ name: "SCALE", type: "number", default: 1 }] },
  { type: "env_rotate3d", category: "environment", label: "rotate 3D x: (RX) y: (RY) z: (RZ)", color: C.environment, shape: "stack", inputs: [{ name: "RX", type: "number", default: 0 }, { name: "RY", type: "number", default: 45 }, { name: "RZ", type: "number", default: 0 }] },
  // — Weather & Effects —
  { type: "env_setweather", category: "environment", label: "set weather to (WEATHER)", color: C.environment, shape: "stack", hint: "clear, rain, snow, fog, storm", inputs: [{ name: "WEATHER", type: "string", default: "clear" }] },
  { type: "env_addparticles", category: "environment", label: "spawn (COUNT) particles (TYPE)", color: C.environment, shape: "stack", hint: "fire, sparkle, smoke, confetti, hearts, stars", inputs: [{ name: "COUNT", type: "number", default: 20 }, { name: "TYPE", type: "string", default: "sparkle" }] },
  { type: "env_clearparticles", category: "environment", label: "clear all particles", color: C.environment, shape: "stack" },
  { type: "env_scenename", category: "environment", label: "current scene name", color: C.environment, shape: "reporter" },

  /* ═══════════════ Effects & Animation (18 blocks) ═══════════════ */
  // — Visual FX —
  { type: "looks_screenflash", category: "looks", label: "flash screen (COLOR) for (SECS) secs", color: C.looks, shape: "stack", inputs: [{ name: "COLOR", type: "string", default: "#ffffff" }, { name: "SECS", type: "number", default: 0.3 }] },
  { type: "looks_screenshake", category: "looks", label: "shake screen (POWER) for (SECS) secs", color: C.looks, shape: "stack", inputs: [{ name: "POWER", type: "number", default: 8 }, { name: "SECS", type: "number", default: 0.4 }] },
  { type: "looks_trail", category: "looks", label: "leave trail (ON_OFF)", color: C.looks, shape: "stack", hint: "on or off", inputs: [{ name: "ON_OFF", type: "string", default: "on" }] },
  { type: "looks_glow", category: "looks", label: "set glow (COLOR) radius (SIZE)", color: C.looks, shape: "stack", inputs: [{ name: "COLOR", type: "string", default: "#ffcc00" }, { name: "SIZE", type: "number", default: 15 }] },
  { type: "looks_pixelate", category: "looks", label: "pixelate (AMOUNT)", color: C.looks, shape: "stack", hint: "0 = normal, 20 = chunky", inputs: [{ name: "AMOUNT", type: "number", default: 0 }] },
  { type: "looks_mosaic", category: "looks", label: "mosaic (COUNT)", color: C.looks, shape: "stack", inputs: [{ name: "COUNT", type: "number", default: 1 }] },
  { type: "looks_fisheye", category: "looks", label: "fisheye (AMOUNT)", color: C.looks, shape: "stack", inputs: [{ name: "AMOUNT", type: "number", default: 0 }] },
  { type: "looks_whirl", category: "looks", label: "whirl (DEGREES)", color: C.looks, shape: "stack", inputs: [{ name: "DEGREES", type: "number", default: 0 }] },
  { type: "looks_brightness", category: "looks", label: "set brightness to (VALUE)", color: C.looks, shape: "stack", inputs: [{ name: "VALUE", type: "number", default: 0 }] },
  { type: "looks_ghost", category: "looks", label: "set ghost effect to (VALUE)", color: C.looks, shape: "stack", hint: "0 = solid, 100 = invisible", inputs: [{ name: "VALUE", type: "number", default: 0 }] },
  // — Character expressions —
  { type: "looks_emote", category: "looks", label: "emote (EMOTE)", color: C.looks, shape: "stack", hint: "happy, sad, angry, surprised, love, dizzy, sleep, cool", inputs: [{ name: "EMOTE", type: "string", default: "happy" }] },
  { type: "looks_setnamebubble", category: "looks", label: "show name tag (ON_OFF)", color: C.looks, shape: "stack", inputs: [{ name: "ON_OFF", type: "string", default: "on" }] },
  // — Fancy motion animations —
  { type: "motion_bounce_anim", category: "motion", label: "bounce (HEIGHT) times (TIMES)", color: C.motion, shape: "stack", inputs: [{ name: "HEIGHT", type: "number", default: 30 }, { name: "TIMES", type: "number", default: 3 }] },
  { type: "motion_spin_anim", category: "motion", label: "spin (DEGREES) in (SECS) secs", color: C.motion, shape: "stack", inputs: [{ name: "DEGREES", type: "number", default: 360 }, { name: "SECS", type: "number", default: 0.5 }] },
  { type: "motion_wobble", category: "motion", label: "wobble (AMOUNT)", color: C.motion, shape: "stack", inputs: [{ name: "AMOUNT", type: "number", default: 15 }] },
  { type: "motion_orbit", category: "motion", label: "orbit x: (CX) y: (CY) radius (R) speed (SPD)", color: C.motion, shape: "stack", inputs: [{ name: "CX", type: "number", default: 0 }, { name: "CY", type: "number", default: 0 }, { name: "R", type: "number", default: 80 }, { name: "SPD", type: "number", default: 2 }] },
  { type: "motion_followmouse", category: "motion", label: "follow mouse speed (SPEED)", color: C.motion, shape: "stack", inputs: [{ name: "SPEED", type: "number", default: 5 }] },
  { type: "motion_patrol", category: "motion", label: "patrol from x: (X1) to x: (X2) speed (SPEED)", color: C.motion, shape: "stack", inputs: [{ name: "X1", type: "number", default: -100 }, { name: "X2", type: "number", default: 100 }, { name: "SPEED", type: "number", default: 3 }] },

  /* ═══════════════ Unity 3D — Player (8 blocks) ═══════════════ */
  { type: "unity_move",         category: "unity", label: "3D move x: (X) y: (Y) z: (Z)",        color: C.unity, shape: "stack", group: "Player", inputs: [{ name: "X", type: "number", default: 0 }, { name: "Y", type: "number", default: 0 }, { name: "Z", type: "number", default: 1 }] },
  { type: "unity_setposition",  category: "unity", label: "3D set position x: (X) y: (Y) z: (Z)", color: C.unity, shape: "stack", group: "Player", inputs: [{ name: "X", type: "number", default: 0 }, { name: "Y", type: "number", default: 0 }, { name: "Z", type: "number", default: 0 }] },
  { type: "unity_rotate",       category: "unity", label: "3D rotate (AXIS) axis (DEGREES)°",      color: C.unity, shape: "stack", group: "Player", inputs: [{ name: "AXIS", type: "string", default: "y" }, { name: "DEGREES", type: "number", default: 45 }] },
  { type: "unity_setrotation",  category: "unity", label: "3D set rotation x: (X) y: (Y) z: (Z)", color: C.unity, shape: "stack", group: "Player", inputs: [{ name: "X", type: "number", default: 0 }, { name: "Y", type: "number", default: 0 }, { name: "Z", type: "number", default: 0 }] },
  { type: "unity_setscale",     category: "unity", label: "3D set scale (SCALE)",                  color: C.unity, shape: "stack", group: "Player", inputs: [{ name: "SCALE", type: "number", default: 1 }] },
  { type: "unity_setcolor",     category: "unity", label: "3D set color r: (R) g: (G) b: (B)",     color: C.unity, shape: "stack", group: "Player", hint: "Values 0–1", inputs: [{ name: "R", type: "number", default: 1 }, { name: "G", type: "number", default: 0.5 }, { name: "B", type: "number", default: 0 }] },
  { type: "unity_setspeed",     category: "unity", label: "3D set speed (VALUE)",                  color: C.unity, shape: "stack", group: "Player", inputs: [{ name: "VALUE", type: "number", default: 5 }] },
  { type: "unity_setjumpforce", category: "unity", label: "3D set jump force (VALUE)",             color: C.unity, shape: "stack", group: "Player", inputs: [{ name: "VALUE", type: "number", default: 7 }] },
  { type: "unity_jump",         category: "unity", label: "3D jump!",                              color: C.unity, shape: "stack", group: "Player" },
  { type: "unity_applyforce",   category: "unity", label: "3D apply force x: (X) y: (Y) z: (Z)",  color: C.unity, shape: "stack", group: "Player", inputs: [{ name: "X", type: "number", default: 0 }, { name: "Y", type: "number", default: 10 }, { name: "Z", type: "number", default: 0 }] },
  { type: "unity_setgravity",   category: "unity", label: "3D set gravity (VALUE)",                color: C.unity, shape: "stack", group: "Player", inputs: [{ name: "VALUE", type: "number", default: 9.8 }] },
  { type: "unity_playanimation",category: "unity", label: "3D play animation (NAME)",              color: C.unity, shape: "stack", group: "Player", inputs: [{ name: "NAME", type: "string", default: "run" }] },

  /* ═══════════════ Unity 3D — Game (12 blocks) ═══════════════ */
  { type: "unity_setscore",   category: "unity", label: "3D set score (VALUE)",               color: C.unity, shape: "stack", group: "Game", inputs: [{ name: "VALUE", type: "number", default: 0 }] },
  { type: "unity_addscore",   category: "unity", label: "3D add (VALUE) to score",            color: C.unity, shape: "stack", group: "Game", inputs: [{ name: "VALUE", type: "number", default: 10 }] },
  { type: "unity_setlives",   category: "unity", label: "3D set lives (VALUE)",               color: C.unity, shape: "stack", group: "Game", inputs: [{ name: "VALUE", type: "number", default: 3 }] },
  { type: "unity_loselife",   category: "unity", label: "3D lose a life",                    color: C.unity, shape: "stack", group: "Game" },
  { type: "unity_addlife",    category: "unity", label: "3D add (VALUE) lives",              color: C.unity, shape: "stack", group: "Game", inputs: [{ name: "VALUE", type: "number", default: 1 }] },
  { type: "unity_sethealth",  category: "unity", label: "3D set health (VALUE) max (MAX)",   color: C.unity, shape: "stack", group: "Game", inputs: [{ name: "VALUE", type: "number", default: 100 }, { name: "MAX", type: "number", default: 100 }] },
  { type: "unity_addhealth",  category: "unity", label: "3D add health (VALUE)",             color: C.unity, shape: "stack", group: "Game", inputs: [{ name: "VALUE", type: "number", default: -10 }] },
  { type: "unity_starttimer", category: "unity", label: "3D start timer (SECONDS) seconds",  color: C.unity, shape: "stack", group: "Game", inputs: [{ name: "SECONDS", type: "number", default: 30 }] },
  { type: "unity_stoptimer",  category: "unity", label: "3D stop timer",                    color: C.unity, shape: "stack", group: "Game" },
  { type: "unity_gameover",   category: "unity", label: "3D game over (REASON)",             color: C.unity, shape: "stack", group: "Game", inputs: [{ name: "REASON", type: "string", default: "Better luck next time!" }] },
  { type: "unity_wingame",    category: "unity", label: "3D win game! (MESSAGE)",            color: C.unity, shape: "stack", group: "Game", inputs: [{ name: "MESSAGE", type: "string", default: "You did it!" }] },
  { type: "unity_setgamemode",category: "unity", label: "3D set game mode (MODE)",           color: C.unity, shape: "stack", group: "Game", hint: "top-down, fps, platformer", inputs: [{ name: "MODE", type: "string", default: "top-down" }] },

  /* ═══════════════ Unity 3D — Objects (10 blocks) ═══════════════ */
  { type: "unity_createobject",    category: "unity", label: "3D create (SHAPE) named (NAME) at x: (X) y: (Y) z: (Z)", color: C.unity, shape: "stack", group: "Objects", hint: "cube sphere cylinder cone torus diamond wall", inputs: [{ name: "SHAPE", type: "string", default: "cube" }, { name: "NAME", type: "string", default: "block1" }, { name: "X", type: "number", default: 3 }, { name: "Y", type: "number", default: 0.5 }, { name: "Z", type: "number", default: 0 }] },
  { type: "unity_destroyobject",   category: "unity", label: "3D destroy (NAME)",                                       color: C.unity, shape: "stack", group: "Objects", inputs: [{ name: "NAME", type: "string", default: "block1" }] },
  { type: "unity_moveobject",      category: "unity", label: "3D move (NAME) x: (X) y: (Y) z: (Z)",                    color: C.unity, shape: "stack", group: "Objects", inputs: [{ name: "NAME", type: "string", default: "block1" }, { name: "X", type: "number", default: 1 }, { name: "Y", type: "number", default: 0 }, { name: "Z", type: "number", default: 0 }] },
  { type: "unity_setobjectpos",    category: "unity", label: "3D set (NAME) position x: (X) y: (Y) z: (Z)",            color: C.unity, shape: "stack", group: "Objects", inputs: [{ name: "NAME", type: "string", default: "block1" }, { name: "X", type: "number", default: 0 }, { name: "Y", type: "number", default: 0 }, { name: "Z", type: "number", default: 0 }] },
  { type: "unity_setobjectcolor",  category: "unity", label: "3D set (NAME) color (COLOR)",                             color: C.unity, shape: "stack", group: "Objects", inputs: [{ name: "NAME", type: "string", default: "block1" }, { name: "COLOR", type: "string", default: "#f43f5e" }] },
  { type: "unity_rotateobject",    category: "unity", label: "3D rotate (NAME) (AXIS) by (DEGREES)°",                   color: C.unity, shape: "stack", group: "Objects", inputs: [{ name: "NAME", type: "string", default: "block1" }, { name: "AXIS", type: "string", default: "y" }, { name: "DEGREES", type: "number", default: 90 }] },
  { type: "unity_setobjectscale",  category: "unity", label: "3D set (NAME) scale (SCALE)",                             color: C.unity, shape: "stack", group: "Objects", inputs: [{ name: "NAME", type: "string", default: "block1" }, { name: "SCALE", type: "number", default: 2 }] },
  { type: "unity_spawn",           category: "unity", label: "3D spawn object at x: (X) y: (Y) z: (Z)",                color: C.unity, shape: "stack", group: "Objects", inputs: [{ name: "X", type: "number", default: 0 }, { name: "Y", type: "number", default: 0 }, { name: "Z", type: "number", default: 0 }] },
  { type: "unity_addplatform",     category: "unity", label: "3D add platform at x: (X) y: (Y) z: (Z) w: (W) d: (D)", color: C.unity, shape: "stack", group: "Objects", inputs: [{ name: "X", type: "number", default: 0 }, { name: "Y", type: "number", default: 2 }, { name: "Z", type: "number", default: 0 }, { name: "W", type: "number", default: 5 }, { name: "D", type: "number", default: 5 }] },
  { type: "unity_addwall",         category: "unity", label: "3D add wall at x: (X) y: (Y) z: (Z) w: (W) h: (H)",     color: C.unity, shape: "stack", group: "Objects", inputs: [{ name: "X", type: "number", default: 0 }, { name: "Y", type: "number", default: 2 }, { name: "Z", type: "number", default: 0 }, { name: "W", type: "number", default: 1 }, { name: "H", type: "number", default: 4 }] },
  { type: "unity_clearobjects",    category: "unity", label: "3D clear all objects",                                    color: C.unity, shape: "stack", group: "Objects" },

  /* ═══════════════ Unity 3D — Enemies & Collectibles (6 blocks) ═══════════════ */
  { type: "unity_addenemy",      category: "unity", label: "3D add (TYPE) enemy at x: (X) z: (Z) speed: (SPEED)",  color: C.unity, shape: "stack", group: "Enemies", hint: "TYPE: chaser ghost spinner patrol", inputs: [{ name: "TYPE", type: "string", default: "chaser" }, { name: "X", type: "number", default: 5 }, { name: "Z", type: "number", default: 5 }, { name: "SPEED", type: "number", default: 2 }] },
  { type: "unity_addcollectible",category: "unity", label: "3D add (TYPE) at x: (X) y: (Y) z: (Z)",               color: C.unity, shape: "stack", group: "Enemies", hint: "TYPE: coin star gem heart diamond powerup", inputs: [{ name: "TYPE", type: "string", default: "coin" }, { name: "X", type: "number", default: 3 }, { name: "Y", type: "number", default: 1 }, { name: "Z", type: "number", default: 3 }] },

  /* ═══════════════ Unity 3D — Scene & FX (14 blocks) ═══════════════ */
  { type: "unity_setbg",         category: "unity", label: "3D set sky r: (R) g: (G) b: (B)",          color: C.unity, shape: "stack", group: "Scene", hint: "Values 0–1", inputs: [{ name: "R", type: "number", default: 0.07 }, { name: "G", type: "number", default: 0.07 }, { name: "B", type: "number", default: 0.4 }] },
  { type: "unity_setsky",        category: "unity", label: "3D set sky color (COLOR)",                  color: C.unity, shape: "stack", group: "Scene", inputs: [{ name: "COLOR", type: "string", default: "#07071a" }] },
  { type: "unity_setfog",        category: "unity", label: "3D set fog density (DENSITY)",              color: C.unity, shape: "stack", group: "Scene", hint: "0 = none, 0.1 = thick", inputs: [{ name: "DENSITY", type: "number", default: 0.02 }] },
  { type: "unity_setambient",    category: "unity", label: "3D set ambient light (VALUE)",              color: C.unity, shape: "stack", group: "Scene", inputs: [{ name: "VALUE", type: "number", default: 0.6 }] },
  { type: "unity_camerashake",   category: "unity", label: "3D camera shake (INTENSITY)",               color: C.unity, shape: "stack", group: "Scene", inputs: [{ name: "INTENSITY", type: "number", default: 0.5 }] },
  { type: "unity_showtext",      category: "unity", label: "3D show (TEXT) for (DURATION) secs",        color: C.unity, shape: "stack", group: "Scene", inputs: [{ name: "TEXT", type: "string", default: "Level 1!" }, { name: "DURATION", type: "number", default: 2 }] },
  { type: "unity_say",           category: "unity", label: "3D say (TEXT)",                             color: C.unity, shape: "stack", group: "Scene", inputs: [{ name: "TEXT", type: "string", default: "Hello from BlockForge!" }] },
  { type: "unity_playsound",     category: "unity", label: "3D play sound (TYPE)",                      color: C.unity, shape: "stack", group: "Scene", hint: "coin jump hurt explode win gameover powerup spawn bounce", inputs: [{ name: "TYPE", type: "string", default: "coin" }] },
  { type: "unity_spawnparticles",category: "unity", label: "3D spawn particles at x: (X) y: (Y) z: (Z)", color: C.unity, shape: "stack", group: "Scene", inputs: [{ name: "X", type: "number", default: 0 }, { name: "Y", type: "number", default: 1 }, { name: "Z", type: "number", default: 0 }] },
  { type: "unity_confetti",      category: "unity", label: "3D confetti burst!",                        color: C.unity, shape: "stack", group: "Scene" },
  { type: "unity_reset",         category: "unity", label: "3D reset scene",                            color: C.unity, shape: "stack", group: "Scene" },
];

export function getBlockDef(type: string): BlockDef | undefined {
  return BLOCK_DEFS.find((b) => b.type === type);
}

export function getCategoryColor(cat: BlockCategory): string {
  return C[cat] || "#888";
}

export const CATEGORIES: { id: BlockCategory; label: string; color: string; icon: string }[] = [
  { id: "game", label: "Game Systems", color: C.game, icon: "🎮" },
  { id: "motion", label: "Motion", color: C.motion, icon: "➤" },
  { id: "looks", label: "Looks", color: C.looks, icon: "◉" },
  { id: "sound", label: "Sound & Music", color: C.sound, icon: "♫" },
  { id: "events", label: "Events", color: C.events, icon: "⚑" },
  { id: "control", label: "Control", color: C.control, icon: "↻" },
  { id: "sensing", label: "Sensing", color: C.sensing, icon: "◔" },
  { id: "operators", label: "Operators", color: C.operators, icon: "+" },
  { id: "variables", label: "Variables", color: C.variables, icon: "≡" },
  { id: "lists", label: "Lists", color: C.lists, icon: "☰" },
  { id: "environment", label: "3D Environments", color: C.environment, icon: "🌍" },
  { id: "physics", label: "Physics", color: C.physics, icon: "⊕" },
  { id: "custom", label: "My Blocks", color: C.custom, icon: "✦" },
  { id: "pen", label: "Pen+", color: C.pen, icon: "✏" },
  { id: "ai", label: "AI", color: C.ai, icon: "✧" },
  { id: "unity", label: "Unity 3D", color: C.unity, icon: "🎮" },
];
